### PR TITLE
Problem: (CRO-503) No way to calculate square root of Milli

### PR DESCRIPTION
**Pull request by devashishdxt**
Solution: Implemented [Babylonian Method](https://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Babylonian_method) to calculate square root.

### CODE REVIEW

**Comment by lezzokafka** [comment]
Heron's method ROCKS!

**Comment by lezzokafka** [comment]
Reminder:
Changing `TendermintVotePower` struct to fit Milli

**Comment by tomtau** [comment]
bors retry

**Comment by leejw51crypto** [comment]
i'm reviewing

**Pull request merged**
