### PR TITLE
Problem (Fix #1050): No integration-tests CI running in the cloud automatically

### LINKED ISSUE #1050: Problem: No integration-tests CI running in the cloud automatically
Since the scripts for building and running mock version of integration-tests are in place, it's now trivial to setup a mock version of drone config(`.drone.mock.yml`) which can runs on [drone cloud](https://cloud.drone.io/) automatically.

### PR DESCRIPTION
**Pull request by yihuang**
Solution:
- Add mock drone to run integration-tests on cloud.drone.io
- Use cargo-make to do coverage
- Prebuilt kcov in chain-test image
- Change 127.0.0.1 -> localhost for executing test on cloud.drone.io

Needs to update image `cryptocom/chain-test:latest` first:
```
$ docker build -f docker/Dockerfile.new --target TEST -t cryptocom/chain-test:latest .
$ docker push cryptocom/chain-test:latest
```

Add `CODECOV_TOKEN` into drone secret for upload coverage report to codecov.io

### CODE REVIEW

**Comment by yihuang** [comment]
Still no able to run integration-tests so far, the processes can not find each other (tried both `127.0.0.1` and `localhost`).
`drone exec` locally works ok though.

**Comment by tomtau** [comment]
bors try

**Comment by tomtau** [comment]
@yihuang one other problem the status name ("continuous-integration/drone/push") collides between the cloud and custom CI... not sure if it's possible to configure it somewhere

**Comment by tomtau** [comment]
@yihuang seems it may be possible with "DRONE_STATUS_NAME" environment variable, I can try

**Comment by yihuang** [comment]
> @yihuang I think it's because of the trigger configuration -- it's running here: https://cloud.drone.io/crypto-com/chain/1

Oh, I mean the integration-tests runs failed, the processes seems unable to connect to each other.

**Comment by tomtau** [comment]
bors try

**Comment by tomtau** [comment]
@yihuang https://github.com/crypto-com/chain/pull/1053 just fixed the status check name

**Comment by tomtau** [comment]
@yihuang ad localhost/127.0.0.1 -- I think there may have been a similar issue on Travis CI when it executed integration tests -- @calvinaco may know

**Comment by yihuang** [comment]
> @yihuang ad localhost/127.0.0.1 -- I think there may have been a similar issue on Travis CI when it executed integration tests -- @calvinaco may know

On `cloud.drone.io`, the actual port binded is not the port you specified.
```
nc -l 10000 &
netstat -anp
```
Output:
```
Active Internet connections (servers and established)
--
61 | Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
62 | tcp        0      0 127.0.0.11:39267        0.0.0.0:*               LISTEN      -
63 | tcp        0      0 0.0.0.0:38027           0.0.0.0:*               LISTEN      451/nc
...
```

**Comment by calvinlauco** [comment]
@tomtau @yihuang 
I have done some investigation and here are what my observations so far:

1. On cloud.drone.io (Drone in general), when you provide an image, all the commands are run inside the container
2. Next, I try to pull the image and try locally, I found that random port reported from `nc` is due to another error. I further verify it by creating a simple Node.js server on a particular port (3000) and it is bound to the same port.
image
3. I checked `/etc/host` inside the container, also seems reasonable to me
```
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	d764271e1173
```

**Comment by yihuang** [comment]
> I think Mac is different from Debian. I tried the same command on Mac it's working. But in Debain I think should use -p to specify a listening port in nc

Great finding 😄. Now the `nc` test script runs fine now, so it's not the port problem. I guess I need to look at the integration-tests problem again.

**Comment by yihuang** [comment]
I know the problem now, it's simply timeouted, on `cloud.drone.io`, the timing to execute tasks could veries a lot. it could due to their resource scheduling. I enlarged the timeout for now.

**Comment by yihuang** [comment]
I think I just find the problem, `cargo test` will override the executables with sgx version, so when running integration tests, the executables are actually sgx version. I made a standalone script to run unit tests with features.

**Comment by tomtau** [comment]
bors try

**Pull request merged**
