### PR TITLE
Problem: (CRO-511) Dockerfile and integration tests are inefficient

### PR DESCRIPTION
**Pull request by calvinaco**
This PR includes several improvements to speed up integration test setup and execution:
- Reuse built docker image to generate genesis and wallet
  - Before the PR `chain` code has to be built twice
- Generalize `chain` docker image and use pre-built Tendermint from DockerHub
- Optimize `chain` and `chain-tx-enclave` image to reduce layers to be re-built on code changes
- Use whitelisting of `.dockerignore` to reduce number of docker image to be re-built on code changes

### CODE REVIEW

**Comment by calvinlauco** [comment]
> looks good, just before merging this via -- @calvinaco could you squash the commits (rebased on the latest master) + have the commit message as in the PR ("Problem: ...(\n\n)Solution: ...")

Sure, done!

**Comment by calvinaco** [comment]
The `docker-compose` logs throws I/O error. I will fix it first.

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by tomtau** [comment]
@calvinaco could you squash commits (rebase on latest master)?

**Comment by calvinaco** [comment]
> @calvinaco could you squash commits (rebase on latest master)?

Should be good now.

**Pull request merged**
