### PR TITLE
Problem:(CRO-547) no launcher for sub processes

### PR DESCRIPTION
**Pull request by linfeng-crypto**
solution:
add a makefile based launcher, and make integration test use the launcher

### CODE REVIEW

**Comment by tomtau** [comment]
bors try

**Comment by tomtau** [comment]
bors try

**Comment by linfeng-crypto** [comment]
> Travis CI fails building integration tests
> https://travis-ci.org/crypto-com/chain/jobs/637240915#L1845
> 
> seems a similar issue to [#884 (review)](https://github.com/crypto-com/chain/pull/884#pullrequestreview-342938692)

forgot to update the `.dockerignore`

**Comment by tomtau** [comment]
bors try

**Pull request merged**
