### PR TITLE
Problem (Fix #853): multi-node integration tests not executed on CI

### LINKED ISSUE #853: Problem: multi-node integration tests not executed on CI
Most of the multi-node integration tests *don't* need spinning up any enclaves (can use the mock compilation or use the SW emulation mode), as all transactions are public (unjail, nodejoin...) and entirely processed by chain-abci.

The current pipeline was disabled mainly because it wasn't stable and didn't do any cleaning: https://github.com/crypto-com/chain/blob/master/.drone.yml#L126

Instead of having a separate pipeline, the multi-node integration tests would ideally be added to the existing integration test pipeline -- either on Travis CI or on Drone.

@leejw51crypto Jason can help with this

### PR DESCRIPTION
**Pull request by yihuang**
Solution:
- new multi-node integration tests for jail and join.
- add a multinode-tests step in default drone pipeline.

Known problem:
- The last step of `jail` and `join` test doesn't succeed, because after `unjail` and `joinnode` request, the count of validators don't increase. They are commented out currently, uncomment them after the bug fixed.

### CODE REVIEW

**Comment by tomtau** [comment]
bors try

**Comment by tomtau** [comment]
bors try-

**Comment by tomtau** [comment]
For the known problem -- I think it should be this: https://github.com/crypto-com/chain/issues/930 ?

**Comment by yihuang** [comment]
> For the known problem -- I think it should be this: #930 ?

Yes, exactly.

**Comment by tomtau** [comment]
bors try

**Comment by tomtau** [comment]
bors try

**Comment by yihuang** [comment]
> * continuous-integration/drone/push

This happens occationally when restarting node.
```
[2020-01-21T06:00:44Z INFO  chain_abci::app::app_init] historical data is stored
--
389 | thread 'main' panicked at 'enclave sanity check failed (either a binary for a different network is used or there is a problem with enclave process), enclave app hash: None (chain-abci app hash: 5a47efdbc03d2c37e824cfed4d1bd8f2616b4d1ed2d8e9bde37af54d0e829517)', chain-abci/src/app/app_init.rs:421:21
``

**Comment by tomtau** [comment]
> > * continuous-integration/drone/push
> 
> This happens occationally when restarting node.
> 
> ```
> [2020-01-21T06:00:44Z INFO  chain_abci::app::app_init] historical data is stored
> --
> 389 | thread 'main' panicked at 'enclave sanity check failed (either a binary for a different network is used or there is a problem with enclave process), enclave app hash: None (chain-abci app hash: 5a47efdbc03d2c37e824cfed4d1bd8f2616b4d1ed2d8e9bde37af54d0e829517)', chain-abci/src/app/app_init.rs:421:21
> ```
> 
> Also, there are another problem appear when testing locally after rebase, deposit transaction seems to has some problems.

```
[2020-01-21T06:00:35Z INFO  tx_validation_app::server] running zmq server
698	[2020-01-21T06:00:35Z ERROR tx_validation_app::server] app hash not match
699	[2020-01-21T06:00:37Z ERROR tx_validation_app::server] app hash not match
700	[2020-01-21T06:00:38Z ERROR tx_validation_app::server] app hash not match
701	[2020-01-21T06:00:40Z ERROR tx_validation_app::server] app hash not match
702	[2020-01-21T06:00:44Z ERROR tx_validation_app::server] app hash not match
```

seems the enclave storage isn't cleared? Is it perhaps from the single node tests?

**Comment by yihuang** [comment]
> > > * continuous-integration/drone/push
> > 
> > 
> > This happens occationally when restarting node.
> > ```
> > [2020-01-21T06:00:44Z INFO  chain_abci::app::app_init] historical data is stored
> > --
> > 389 | thread 'main' panicked at 'enclave sanity check failed (either a binary for a different network is used or there is a problem with enclave process), enclave app hash: None (chain-abci app hash: 5a47efdbc03d2c37e824cfed4d1bd8f2616b4d1ed2d8e9bde37af54d0e829517)', chain-abci/src/app/app_init.rs:421:21
> > ```
> > 
> > 
> > Also, there are another problem appear when testing locally after rebase, deposit transaction seems to has some problems.
> 
> ```
> [2020-01-21T06:00:35Z INFO  tx_validation_app::server] running zmq server
> 698	[2020-01-21T06:00:35Z ERROR tx_validation_app::server] app hash not match
> 699	[2020-01-21T06:00:37Z ERROR tx_validation_app::server] app hash not match
> 700	[2020-01-21T06:00:38Z ERROR tx_validation_app::server] app hash not match
> 701	[2020-01-21T06:00:40Z ERROR tx_validation_app::server] app hash not match
> 702	[2020-01-21T06:00:44Z ERROR tx_validation_app::server] app hash not match
> ```
> 
> seems the enclave storage isn't cleared? Is it perhaps from the single node tests?

It's jail test, the code tries to stop node2, wait for 13 blocks, and start it again, node2 fails to startup. here.

**Comment by tomtau** [comment]
> > > > * continuous-integration/drone/push
> > > 
> > > 
> > > This happens occationally when restarting node.
> > > ```
> > > [2020-01-21T06:00:44Z INFO  chain_abci::app::app_init] historical data is stored
> > > --
> > > 389 | thread 'main' panicked at 'enclave sanity check failed (either a binary for a different network is used or there is a problem with enclave process), enclave app hash: None (chain-abci app hash: 5a47efdbc03d2c37e824cfed4d1bd8f2616b4d1ed2d8e9bde37af54d0e829517)', chain-abci/src/app/app_init.rs:421:21
> > > ```
> > > 
> > > 
> > > Also, there are another problem appear when testing locally after rebase, deposit transaction seems to has some problems.
> > 
> > 
> > ```
> > [2020-01-21T06:00:35Z INFO  tx_validation_app::server] running zmq server
> > 698	[2020-01-21T06:00:35Z ERROR tx_validation_app::server] app hash not match
> > 699	[2020-01-21T06:00:37Z ERROR tx_validation_app::server] app hash not match
> > 700	[2020-01-21T06:00:38Z ERROR tx_validation_app::server] app hash not match
> > 701	[2020-01-21T06:00:40Z ERROR tx_validation_app::server] app hash not match
> > 702	[2020-01-21T06:00:44Z ERROR tx_validation_app::server] app hash not match
> > ```
> > 
> > 
> > seems the enclave storage isn't cleared? Is it perhaps from the single node tests?
> 
> It's jail test, the code tries to stop node2, wait for 13 blocks, and start it again, node2 fails to startup.
> You need to scroll up a lot to see the testing logs.

does the shutdown happen in this order:
1. Tendermint
2. chain-abci
3. tx_validation_app
?

**Comment by yihuang** [comment]
> > > > > * continuous-integration/drone/push
> > > > 
> > > > 
> > > > This happens occationally when restarting node.
> > > > ```
> > > > [2020-01-21T06:00:44Z INFO  chain_abci::app::app_init] historical data is stored
> > > > --
> > > > 389 | thread 'main' panicked at 'enclave sanity check failed (either a binary for a different network is used or there is a problem with enclave process), enclave app hash: None (chain-abci app hash: 5a47efdbc03d2c37e824cfed4d1bd8f2616b4d1ed2d8e9bde37af54d0e829517)', chain-abci/src/app/app_init.rs:421:21
> > > > ```
> > > > 
> > > > 
> > > > Also, there are another problem appear when testing locally after rebase, deposit transaction seems to has some problems.
> > > 
> > > 
> > > ```
> > > [2020-01-21T06:00:35Z INFO  tx_validation_app::server] running zmq server
> > > 698	[2020-01-21T06:00:35Z ERROR tx_validation_app::server] app hash not match
> > > 699	[2020-01-21T06:00:37Z ERROR tx_validation_app::server] app hash not match
> > > 700	[2020-01-21T06:00:38Z ERROR tx_validation_app::server] app hash not match
> > > 701	[2020-01-21T06:00:40Z ERROR tx_validation_app::server] app hash not match
> > > 702	[2020-01-21T06:00:44Z ERROR tx_validation_app::server] app hash not match
> > > ```
> > > 
> > > 
> > > seems the enclave storage isn't cleared? Is it perhaps from the single node tests?
> > 
> > 
> > It's jail test, the code tries to stop node2, wait for 13 blocks, and start it again, node2 fails to startup.
> > You need to scroll up a lot to see the testing logs.
> 
> does the shutdown happen in this order:
> 
> 1. Tendermint
> 2. chain-abci
> 3. tx_validation_app
>    ?

No, it don't wait for one by one.

**Comment by yihuang** [comment]
Now stop sequence is changed to:
```
stop tendermint
wait
stop chain-abci
wait
stop all other processes.
```

**Comment by tomtau** [comment]
bors try

**Comment by yihuang** [comment]
Still the same problem, strange, I've run several rounds locally successfully.

From the log, we can see the stop sequence are in effects:
```
Stop node2
--
96 | stop tendermint node2
97 | 2020-01-21 08:25:22,406 INFO waiting for tendermint-node2 to stop
98 | 2020-01-21 08:25:22,416 INFO stopped: tendermint-node2 (exit status 0)
99 | stop chain-abci node2
100 | 2020-01-21 08:25:22,417 INFO waiting for chain-abci-node2 to stop
101 | 2020-01-21 08:25:22,418 INFO stopped: chain-abci-node2 (terminated by SIGTERM)
102 | 2020-01-21 08:25:22,420 INFO stopped: client-rpc-node2 (terminated by SIGTERM)
103 | 2020-01-21 08:25:22,420 INFO waiting for tx-validation-node2 to stop
104 | 2020-01-21 08:25:22,420 INFO waiting for tx-query-node2 to stop
105 | 2020-01-21 08:25:22,820 INFO stopped: tx-validation-node2 (terminated by SIGTERM)
106 | 2020-01-21 08:25:22,820 INFO stopped: tx-query-node2 (terminated by SIGTERM)
```

**Comment by yihuang** [comment]
Added 5 seconds sleep between stopping chain-abci and other processes(mainly tx-validation-app), let's  see how that goes?

**Comment by tomtau** [comment]
bors try

**Comment by tomtau** [comment]
seems to work -- perhaps squash the commits?

**Comment by tomtau** [comment]
bors try

**Comment by tomtau** [comment]
bors retry

**Pull request merged**
