### PR TITLE
Problem (Fix #1518): reward multi-node integration test fails on TM 0.33.3/4

### LINKED ISSUE #1518: Problem: reward multi-node integration test fails on TM 0.33.3/4
```
Preparing... reward
354	Prepared succesfully ./data 26650 SGX
355	Startup...
356	Wait for http port 26659
357	[Thu Apr 30 11:57:36 UTC 2020] Http port 26659 not available yet, sleep 2 seconds and retry
358	2020-04-30 11:57:36,737 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
359	2020-04-30 11:57:36,739 INFO RPC interface 'supervisor' initialized
360	2020-04-30 11:57:36,739 CRIT Server 'unix_http_server' running without any HTTP authentication checking
361	2020-04-30 11:57:36,739 INFO supervisord started with pid 3446
362	2020-04-30 11:57:37,742 INFO spawned: 'tx-query-node0' with pid 3452
363	2020-04-30 11:57:37,743 INFO spawned: 'chain-abci-node0' with pid 3453
364	2020-04-30 11:57:37,745 INFO spawned: 'tendermint-node0' with pid 3454
365	2020-04-30 11:57:37,746 INFO spawned: 'client-rpc-node0' with pid 3455
366	2020-04-30 11:57:37,747 INFO spawned: 'tx-query-node1' with pid 3456
367	2020-04-30 11:57:37,748 INFO spawned: 'chain-abci-node1' with pid 3457
368	2020-04-30 11:57:37,750 INFO spawned: 'tendermint-node1' with pid 3458
369	2020-04-30 11:57:37,751 INFO spawned: 'client-rpc-node1' with pid 3459
370	2020-04-30 11:57:37,752 INFO spawned: 'tx-query-node2' with pid 3460
371	2020-04-30 11:57:37,754 INFO spawned: 'chain-abci-node2' with pid 3461
372	2020-04-30 11:57:37,759 INFO spawned: 'tendermint-node2' with pid 3462
373	2020-04-30 11:57:37,761 INFO spawned: 'client-rpc-node2' with pid 3463
374	[Thu Apr 30 11:57:38 UTC 2020] Http port 26659 not available yet, sleep 2 seconds and retry
375	2020-04-30 11:57:39,220 INFO success: tx-query-node0 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
376	2020-04-30 11:57:39,220 INFO success: chain-abci-node0 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
377	2020-04-30 11:57:39,220 INFO success: tendermint-node0 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
378	2020-04-30 11:57:39,220 INFO success: client-rpc-node0 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
379	2020-04-30 11:57:39,220 INFO success: tx-query-node1 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
380	2020-04-30 11:57:39,220 INFO success: chain-abci-node1 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
381	2020-04-30 11:57:39,220 INFO success: tendermint-node1 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
382	2020-04-30 11:57:39,221 INFO success: client-rpc-node1 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
383	2020-04-30 11:57:39,221 INFO success: tx-query-node2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
384	2020-04-30 11:57:39,221 INFO success: chain-abci-node2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
385	2020-04-30 11:57:39,221 INFO success: tendermint-node2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
386	2020-04-30 11:57:39,221 INFO success: client-rpc-node2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
387	[Thu Apr 30 11:57:40 UTC 2020] Http port 26659 not available yet, sleep 2 seconds and retry
388	[Thu Apr 30 11:57:42 UTC 2020] Http port 26659 not available yet, sleep 2 seconds and retry
389	[Thu Apr 30 11:57:44 UTC 2020] Http port 26659 not available yet, sleep 2 seconds and retry
390	[Thu Apr 30 11:57:46 UTC 2020] Http port 26659 not available yet, sleep 2 seconds and retry
391	[Thu Apr 30 11:57:48 UTC 2020] Http port 26659 not available yet, sleep 2 seconds and retry
392	[Thu Apr 30 11:57:50 UTC 2020] Http port 26659 not available yet, sleep 2 seconds and retry
393	[Thu Apr 30 11:57:52 UTC 2020] Http port 26659 not available yet, sleep 2 seconds and retry
394	[Thu Apr 30 11:57:54 UTC 2020] Http port 26659 not available yet, sleep 2 seconds and retry
395	[Thu Apr 30 11:57:56 UTC 2020] Http port 26659 not available yet, sleep 2 seconds and retry
396	[Thu Apr 30 11:57:58 UTC 2020] Http port 26659 not available yet, sleep 2 seconds and retry
397	Http port 26659 is available now
398	Traceback (most recent call last):
399	  File "./multinode/reward_test.py", line 46, in <module>
400	    assert int(state['bonded']) == init_bonded + minted // 2
401	AssertionError
402	==> data/logs/chain-abci-node0.log <==
403	[2020-04-30T11:57:37Z INFO  chain_abci] network=Devnet network_id=AB
```

### PR DESCRIPTION
**Pull request by yihuang**
Solution:
- Make reward integration tests more stable
- Also upgrade the tendermint version in Dockerfile and Makefile

### CODE REVIEW

**Comment by yihuang** [comment]
> not sure if the failure is related:
> 
> ```
> 
> module=main nodeInfo="{ProtocolVersion:{P2P:7 Block:10 App:1} DefaultNodeID:e3d428511f5cf1c9e57c57dc85383088a4c21b0e ListenAddr:tcp://0.0.0.0:26676 Network:test-chain-y3m1e6-AB Version:0.33.2 Channels:4020212223303800 Moniker:node2 Other:{TxIndex:on RPCAddress:tcp://0.0.0.0:26677}}"
> --
> 830 | panic: Failed to process committed block (2:886824B499666E7010BD950D4C4961973AF43B34263254282E770DB2403119D6): wrong Block.Header.Version. Expected {10 1}, got {10 0}
> ```

Strange, does it means expect app version to be `1`, but got a `0`?

**Comment by tomtau** [comment]
> > not sure if the failure is related:
> > ```
> > 
> > module=main nodeInfo="{ProtocolVersion:{P2P:7 Block:10 App:1} DefaultNodeID:e3d428511f5cf1c9e57c57dc85383088a4c21b0e ListenAddr:tcp://0.0.0.0:26676 Network:test-chain-y3m1e6-AB Version:0.33.2 Channels:4020212223303800 Moniker:node2 Other:{TxIndex:on RPCAddress:tcp://0.0.0.0:26677}}"
> > --
> > 830 | panic: Failed to process committed block (2:886824B499666E7010BD950D4C4961973AF43B34263254282E770DB2403119D6): wrong Block.Header.Version. Expected {10 1}, got {10 0}
> > ```
> 
> Strange, does it means that expecting app version to be `1`, but got a `0`?

Yes, that's what it says. For some reason, in node2, it first stars with "0":
```
=> data/logs/tendermint-node2.log <==
800	E[2020-05-04|01:05:12.154] abci.socketClient failed to connect to tcp://127.0.0.1:26678.  Retrying... module=abci-client connection=query err="dial tcp 127.0.0.1:26678: connect: connection refused"
801	E[2020-05-04|01:05:15.154] abci.socketClient failed to connect to tcp://127.0.0.1:26678.  Retrying... module=abci-client connection=query err="dial tcp 127.0.0.1:26678: connect: connection refused"
802	E[2020-05-04|01:05:18.155] abci.socketClient failed to connect to tcp://127.0.0.1:26678.  Retrying... module=abci-client connection=query err="dial tcp 127.0.0.1:26678: connect: connection refused"
803	E[2020-05-04|01:05:21.155] abci.socketClient failed to connect to tcp://127.0.0.1:26678.  Retrying... module=abci-client connection=query err="dial tcp 127.0.0.1:26678: connect: connection refused"
804	E[2020-05-04|01:05:24.156] abci.socketClient failed to connect to tcp://127.0.0.1:26678.  Retrying... module=abci-client connection=query err="dial tcp 127.0.0.1:26678: connect: connection refused"
805	E[2020-05-04|01:05:27.156] abci.socketClient failed to connect to tcp://127.0.0.1:26678.  Retrying... module=abci-client connection=query err="dial tcp 127.0.0.1:26678: connect: connection refused"
806	I[2020-05-04|01:05:30.166] Version info                                 module=main software=0.33.2 block=10 p2p=7
807	I[2020-05-04|01:05:30.169] Starting Node                                module=main impl=Node
808	I[2020-05-04|01:05:30.170] Started node                                 module=main nodeInfo="{ProtocolVersion:{P2P:7 Block:10 App:0} 
```

**Comment by yihuang** [comment]
> > > not sure if the failure is related:
> > > ```
> > > 
> > > module=main nodeInfo="{ProtocolVersion:{P2P:7 Block:10 App:1} DefaultNodeID:e3d428511f5cf1c9e57c57dc85383088a4c21b0e ListenAddr:tcp://0.0.0.0:26676 Network:test-chain-y3m1e6-AB Version:0.33.2 Channels:4020212223303800 Moniker:node2 Other:{TxIndex:on RPCAddress:tcp://0.0.0.0:26677}}"
> > > --
> > > 830 | panic: Failed to process committed block (2:886824B499666E7010BD950D4C4961973AF43B34263254282E770DB2403119D6): wrong Block.Header.Version. Expected {10 1}, got {10 0}
> > > ```
> > 
> > 
> > Strange, does it means that expecting app version to be `1`, but got a `0`?
> 
> Yes, that's what it says. For some reason, in node2, it first stars with "0":

https://github.com/crypto-com/chain/blob/master/chain-abci/src/app/mod.rs#L54
Maybe we should set the version fields in the `else` branch too?

**Comment by tomtau** [comment]
if you can reproduce it, it'll be good to see it with "debug" or "trace" log level on chain-abci -- I don't know if it could be that chain-abci didn't write back/flush responses "in order" (info -> query) and query response was reinterpreted as info (or some bug in tendermint)?
```
==> data/logs/chain-abci-node2.log <==
376	[2020-05-04T01:05:12Z INFO  chain_abci] network=Devnet network_id=AB
377	[2020-05-04T01:05:12Z INFO  chain_abci::enclave_bridge::real] Attempting to launch TX Validation Enclave in debug mode
378	[2020-05-04T01:05:23Z INFO  chain_abci::enclave_bridge::real] [+] Init TX Validation Server Enclave Successful 2!
379	[2020-05-04T01:05:23Z INFO  chain_abci] starting up
380	[2020-05-04T01:05:23Z INFO  chain_abci::enclave_bridge::real] Attempting to launch TX Validation Enclave (for tx-query / zmq) in debug mode
381	[2020-05-04T01:05:29Z INFO  chain_abci::enclave_bridge::real] [+] Init TX Validation Server Enclave (for tx-query / zmq) Successful 3!
382	[2020-05-04T01:05:29Z INFO  chain_abci::enclave_bridge::real] starting zmq server
383	[2020-05-04T01:05:29Z INFO  chain_abci::enclave_bridge::real::server] running zmq server
384	[2020-05-04T01:05:29Z INFO  chain_abci::app::app_init] no last app state stored
385	[2020-05-04T01:05:29Z INFO  chain_abci::app::app_init] enclave connection OK
386	[2020-05-04T01:05:30Z INFO  abci::server] Got connection! TcpStream { addr: V4(127.0.0.1:26678), peer: V4(127.0.0.1:51020), fd: 45 }
387	[2020-05-04T01:05:30Z INFO  abci::server] Got connection! TcpStream { addr: V4(127.0.0.1:26678), peer: V4(127.0.0.1:51022), fd: 46 }
388	[2020-05-04T01:05:30Z INFO  abci::server] Got connection! TcpStream { addr: V4(127.0.0.1:26678), peer: V4(127.0.0.1:51024), fd: 47 }
389	[2020-05-04T01:05:30Z INFO  chain_abci::app] received info request
390	[2020-05-04T01:05:30Z INFO  chain_abci::app] received initchain request
391	[2020-05-04T01:05:30Z WARN  chain_abci::app::app_init] consensus parameters not checked (TODO)
392	[2020-05-04T01:05:30Z INFO  chain_abci::app] received query request
393	[2020-05-04T01:05:30Z INFO  chain_abci::app] received query request
394	[2020-05-04T01:05:30Z INFO  chain_abci::app] received query request
```

**Comment by tomtau** [comment]
> > > > not sure if the failure is related:
> > > > ```
> > > > 
> > > > module=main nodeInfo="{ProtocolVersion:{P2P:7 Block:10 App:1} DefaultNodeID:e3d428511f5cf1c9e57c57dc85383088a4c21b0e ListenAddr:tcp://0.0.0.0:26676 Network:test-chain-y3m1e6-AB Version:0.33.2 Channels:4020212223303800 Moniker:node2 Other:{TxIndex:on RPCAddress:tcp://0.0.0.0:26677}}"
> > > > --
> > > > 830 | panic: Failed to process committed block (2:886824B499666E7010BD950D4C4961973AF43B34263254282E770DB2403119D6): wrong Block.Header.Version. Expected {10 1}, got {10 0}
> > > > ```
> > > 
> > > 
> > > Strange, does it means that expecting app version to be `1`, but got a `0`?
> > 
> > 
> > Yes, that's what it says. For some reason, in node2, it first stars with "0":
> 
> https://github.com/crypto-com/chain/blob/master/chain-abci/src/app/mod.rs#L54
> Maybe we should set the version fields in the `else` branch too?



> > > > not sure if the failure is related:
> > > > ```
> > > > 
> > > > module=main nodeInfo="{ProtocolVersion:{P2P:7 Block:10 App:1} DefaultNodeID:e3d428511f5cf1c9e57c57dc85383088a4c21b0e ListenAddr:tcp://0.0.0.0:26676 Network:test-chain-y3m1e6-AB Version:0.33.2 Channels:4020212223303800 Moniker:node2 Other:{TxIndex:on RPCAddress:tcp://0.0.0.0:26677}}"
> > > > --
> > > > 830 | panic: Failed to process committed block (2:886824B499666E7010BD950D4C4961973AF43B34263254282E770DB2403119D6): wrong Block.Header.Version. Expected {10 1}, got {10 0}
> > > > ```
> > > 
> > > 
> > > Strange, does it means that expecting app version to be `1`, but got a `0`?
> > 
> > 
> > Yes, that's what it says. For some reason, in node2, it first stars with "0":
> 
> https://github.com/crypto-com/chain/blob/master/chain-abci/src/app/mod.rs#L54
> Maybe we should set the version fields in the `else` branch too?

yes, I guess that would be it:
```
            resp.app_version = chain_core::APP_VERSION;
            resp.version = get_version();
```
should be set regardless of other things

**Comment by tomtau** [comment]
opened this issue: https://github.com/crypto-com/chain/issues/1527

**Comment by yihuang** [comment]
> some changes in [aef3d47#diff-0bd126bf04f518f4a4e61a728127dafe](https://github.com/crypto-com/chain/commit/aef3d4709fcb8f87be4336d883f1c92f1a18a1f8#diff-0bd126bf04f518f4a4e61a728127dafe)

Done, fixed the merge conflict.

**Pull request merged**
