### PR TITLE
Problem: (CRO-511) Dockerfile and integration tests are inefficient

### PR DESCRIPTION
**Pull request by calvinaco**

### CODE REVIEW

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try-

**Comment by calvinaco** [comment]
bors try

**Comment by leejw51crypto** [comment]
there is --proxy... error

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try-

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Pull request closed without merging**
