### PR TITLE
Problem: TDBE connection details are not exposed in tendermint RPC

### PR DESCRIPTION
**Pull request by devashishdxt**
Solution: Add ABCI `query` to fetch TDBE connection details

### CODE REVIEW

**Review by tomtau — APPROVED** [review]
bors r+

**Review by tomtau — CHANGES_REQUESTED** [review]
fuzzer target code may need an update too: https://github.com/crypto-com/chain/blob/master/chain-abci/fuzz/fuzz_targets/abci_cycle.rs#L220

**Comment by devashishdxt** [comment]
> fuzzer target code may need an update too: https://github.com/crypto-com/chain/blob/master/chain-abci/fuzz/fuzz_targets/abci_cycle.rs#L220

Done.

**Review by tomtau — APPROVED** [review]
bors r+

**Comment by tomtau** [comment]
bors retry

**Review by leejw51crypto — APPROVED** [review]
lgtm

**Pull request merged**
