### PR TITLE
Problem (Fix #1067): chainbot.py prepare runs slow

### LINKED ISSUE #1067: `chainbot.py prepare` runs slow
`chainbot.py prepare` runs quite slow, especially on multiple nodes setup.
Some preliminary investigation shows most time spent on wallet restore, and there is two execution for each node, so merge these two executions into one can cut the time by half.

### PR DESCRIPTION
**Pull request by yihuang**
Solution:
- Merge two times of wallet restore into one.

> There is also a change to make `test_watch_only_wallet` more stable.

### CODE REVIEW

**Comment by yihuang** [comment]
The wallet sync failure happens again, recorded in #1069 .

**Comment by tomtau** [comment]
bors retry

**Comment by tomtau** [comment]
bors retry

**Comment by tomtau** [comment]
cache problems?

**Comment by tomtau** [comment]
bors retry

**Pull request merged**
