### PR TITLE
Problem: unsafe default option for client-* (fix #1869)

### LINKED ISSUE #1869: Problem: unsafe default option for client-*
"fast-forward" is more advanced feature only applicable to someone running its own full node

### PR DESCRIPTION
**Pull request by leejw51crypto**
disabled fast forward is the default option
--enable-fast-forward to activate `fast forward`

### CODE REVIEW

**Comment by tomtau** [comment]
https://github.com/crypto-com/chain/issues/1934

**Comment by leejw51crypto** [comment]
what's bors log?

**Comment by tomtau** [comment]
> what's bors log?

it probably due to the other PR: https://github.com/crypto-com/chain/pull/1926#pullrequestreview-446997437

**Comment by leejw51crypto** [comment]
fixed integration test

**Pull request merged**
