### PR TITLE
Problem: legacy redeem address textual conversion code (fix #2150)

### LINKED ISSUE #2150: Problem: legacy redeem address textual conversion code
https://github.com/crypto-com/chain/blob/master/chain-core/src/init/address.rs#L391
`to_cro` and `from_cro` on `RedeemAddress` generally don't make sense with the existing conventions / aren't used anywhere besides the test above

### PR DESCRIPTION
**Pull request by leejw51crypto**
Solution: remove un-necessary unit test

### CODE REVIEW

**Review by tomtau — CHANGES_REQUESTED** [review]
this can also be removed: https://github.com/crypto-com/chain/blob/master/chain-core/src/init/address.rs#L199 ?

**Comment by leejw51crypto** [comment]
yes, that need to be removed, too.
i'll remove it

**Review by tomtau — CHANGES_REQUESTED** [review]
a few unused imports:
https://github.com/crypto-com/chain/runs/1020049723#step:6:770

**Comment by leejw51crypto** [comment]
ok, i'll check that

**Comment by tomtau** [comment]
squash commits?

**Comment by leejw51crypto** [comment]
ok

**Pull request merged**
