### PR TITLE
Problem: Integration tests does not work for cross-platforms

### PR DESCRIPTION
**Pull request by calvinlauco**
Solution: Change commands to be compatible in Mac in Linux platforms

### CODE REVIEW

**Comment by calvinaco** [comment]
bors try

**Comment by leejw51crypto** [comment]
1. tmux login
2. ./prepare.sh
3. . ./env.sh
docker-compose up
```
ERROR: for 66b56a4527e9_integration-tests_tendermint_1  Cannot create container for service tendermint: invalid volume specification: '1a6d16965cb2768d2e43e848074d4ba73d25a34f9ddcfd465c155b5959b110bb:]:rw': invalid mount config for type "volume": invalid mount path: ']' mount 
Recreating integration-tests_chain-abci_1                      ... done
```

**Comment by leejw51** [comment]
os is ubuntu16

**Comment by calvinlauco** [comment]
> Maybe to solve these cross-platform issues, it'll be the simplest to switch to Python scripts -- I don't know if all of integration test setup is supported, but I guess most of it is there @yihuang https://github.com/yihuang/crypto-chain-bot

I agree. I am closing this task in favor of migrating to the bot solution.

**Pull request closed without merging**
