### PR TITLE
Problem: (CRO-577) Client uses weak hashing algorithm for passwords

### PR DESCRIPTION
**Pull request by devashishdxt**
Solution: Started using `rust-argon2`

### CODE REVIEW

**Comment by devashishdxt** [comment]
bors try

**Comment by devashishdxt** [comment]
> running the integration test now takes 2x time (before it was around 20 minutes from scratch, now around 40).
> passing around the hmac-ed keys from this strengthened secret (instead of re-computing in every request) as discussed on Slack should be preferable -- but I guess that would be require more changes in the client + tests. Perhaps in a different PR?
> 
> @leejw51crypto approved this but I guess if this gets merged, be prepared that on Monday, he'd be like "strang-eee, why is client so slow?" 😂

Passing around HMAC-ed keys will take substantial amount of work on client side. Both in backend and frontend. We can do that in different PRs. One way to reduce integration test times is to keep using `blake2` for debug builds and only use `argon2` for release builds. Any comments?

**Comment by tomtau** [comment]
> > running the integration test now takes 2x time (before it was around 20 minutes from scratch, now around 40).
> > passing around the hmac-ed keys from this strengthened secret (instead of re-computing in every request) as discussed on Slack should be preferable -- but I guess that would be require more changes in the client + tests. Perhaps in a different PR?
> > @leejw51crypto approved this but I guess if this gets merged, be prepared that on Monday, he'd be like "strang-eee, why is client so slow?" 😂
> 
> Passing around HMAC-ed keys will take substantial amount of work on client side. Both in backend and frontend. We can do that in different PRs. One way to reduce integration test times is to keep using `blake2` for debug builds and only use `argon2` for release builds. Any comments?

 it's fine -- slow tests will annoy and motivate to prioritise that client work.

bors r+

**Comment by leejw51crypto** [comment]
how about conditional compilation for integration test?
but password generation takes really tons of time, we may consider some lightway

**Comment by devashishdxt** [comment]
> @leejw51crypto approved this but I guess if this gets merged, be prepared that on Monday, he'd be like "strang-eee, why is client so slow?" 😂

Turns out to be true 😂

**Comment by leejw51crypto** [comment]
because it's too heavy operation, login attempt itself can be used as an attack.
server performance will be impacted much.
i propose like this
1. blacke2b
2. make argon2 hash in client side , <- wondering is it possible in javascript?
3. HMAC token method <- yes, it's viable option

**Pull request merged**
