### PR TITLE
Problem: (CRO-582) Create transfer address is not re-usable

### PR DESCRIPTION
**Pull request by calvinlauco**
Solution: Extracted MultiSigAddress from root_hash service to serve single responsibility

---
Remarks:
- This PR is a pre-requisite of the JS library by making components re-usable by JS
- Removed n(total_signers) field because it is implied from len of public keys

### CODE REVIEW

**Comment by calvinaco** [comment]
bors try

**Comment by tomtau** [comment]
bors retry

**Comment by tomtau** [comment]
@calvinlauco can you squash the commits?

**Comment by calvinaco** [comment]
> looks ok -- note that the multi-sig addresses can have more general conditions, e.g. there are signers A,B,C and it could be signed by either A or B&C... and this client API doesn't allow/expose that, but it could perhaps be added later when required?

Yes, I agree. Flexible signing pairs can have a separate task for it. This task focus more on extracting and refactoring existing logic to be re-usable component.

> @calvinlauco can you squash the commits?

Ok, will squash it now.

**Comment by calvinaco** [comment]
bors retry

**Pull request merged**
