### PR TITLE
Problem: (CRO-238) No passphrase confirmation in client cli during new wallet creation

### PR DESCRIPTION
**Pull request by devashishdxt**
Solution: Added passphrase confirmation during new wallet creation

### CODE REVIEW

**Comment by calvinlauco** [comment]
This could break the integration test, the fix should be just to echo the password twice in `integration_tests/prepare.sh` during create wallet

**Comment by tomtau** [comment]
> This could break the integration test, the fix should be just to echo the password twice in `integration_tests/prepare.sh` during create wallet

seems the integration test has been broken for some time due to other changes

**Comment by calvinlauco** [comment]
Oh, let me fix it after this is merged then.

**Comment by devashishdxt** [comment]
> This could break the integration test, the fix should be just to echo the password twice in `integration_tests/prepare.sh` during create wallet

I've changed `create_wallet()` in `prepare.sh`.

**Pull request merged**
