### PR TITLE
Problem: (CRO-654) Fix unnoticed warnings

### PR DESCRIPTION
**Pull request by calvinlauco**
Solution: Add checking to CI pipeline and fix existing warnings

### CODE REVIEW

**Comment by calvinlauco** [comment]
I will first test if the TravisCI pipeline works, before applying the fix to existing warnings.

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try-

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors retry

**Comment by calvinaco** [comment]
bors try-

**Comment by calvinaco** [comment]
bors try

**Pull request merged**
