### PR TITLE
Problem (Fix #1468): tendermint v0.33.4 doesn't support showing total…

### LINKED ISSUE #1468: Problem: tendermint v0.33.4 doesn't support showing total no of transaction in block by rpc
In devnet test, one test is to compare no of transaction call to abci with no of transaction in tendermint blocks. 
After upgrade to v0.33.4, tendermint no longer support rpc call that show the no. of all committed transactions in block. Below api no longer work.
`curl -s --location --request GET 'http://localhost:26657/block'  | jq -r .result.block.header.total_txs `

Possible solution: 
1. Get the no. of all committed transactions by enabling prometheus in tendermint config
https://docs.tendermint.com/master/tendermint-core/metrics.html

### PR DESCRIPTION
**Pull request by allthatjazzleo**
Solution:
- Enable prometheus in tendermint devnet config
- add new prometheus port mapping in makefile for tendermint

### CODE REVIEW

**Comment by yihuang** [comment]
> Build failed:
> 
> * [drone-hw/push](http://13.82.172.109/crypto-com/chain/463)

This issue seems occasionally happens after upgrade to tendermint-rs 0.33
Recorded here: https://github.com/crypto-com/chain/issues/1475

**Comment by tomtau** [comment]
bors retry

**Comment by tomtau** [comment]
bors retry

**Pull request merged**
