### PR TITLE
Problem (Fix #1436): Performance of merkle library is not clear

### LINKED ISSUE #1436: Problem: Performance of merkle library is not clear
Benchmark metrics:
- tps
- number of internal nodes
- disk usage

### PR DESCRIPTION
**Pull request by yihuang**
#### Internal node fill rate

10000 stakings per version, commit 1000 versions in memory.

Internal node fill rate: 0.22 - 0.25, when the number of stakings is under 10M.

```
$ cargo run --example jellyfish_nodes -p chain-storage 1000 10000
...
internal/leaf: 65557 / 170000 = 0.3856294117647059
internal avg fill rate: 0.22457174672422472
...
internal/leaf: 807343 / 2060000 = 0.39191407766990294
internal avg fill rate: 0.22197365308177566
...
internal/leaf: 1090517 / 2840000 = 0.3839848591549296
internal avg fill rate: 0.2252667771341483
...
internal/leaf: 3333197 / 10000000 = 0.3333197
internal avg fill rate: 0.2500076503128978
```

#### In memory operations benchmark

```
$ cargo bench -p chain-storage
jellyfish, insert 256   time:   [4.6825 ms 4.6957 ms 4.7107 ms]
jellyfish, insert       time:   [30.993 us 31.144 us 31.313 us]
jellyfish, get_with_proof
                        time:   [15.605 us 15.721 us 15.877 us]
```

#### Disk usage

10000 stakings per version, no pruning.

```
$ cargo run --example disk_storage -p chain-storage /tmp/db 10 10000
$ du -sh /tmp/db
 37M	/tmp/db
$ rm -r /tmp/db
$ cargo run --example disk_storage -p chain-storage /tmp/db 100 10000
$ du -sh /tmp/db
 625M	/tmp/db
```

#### Disk get benchmark

Get staking from db with existing address:

```
$ DBPATH=/tmp/db STAKING_ADDRESS=0000000000000000000000000000000000000000  cargo run --example bench_jellyfish_disk -p chain-storage -- --bench
jellyfish_disk, get_with_proof
                        time:   [505.86 us 511.42 us 517.79 us]
```

Not exist address:
```
$ DBPATH=/tmp/db STAKING_ADDRESS=ffffffffffffffffffffffffffffffffffffffff cargo run --example bench_jellyfish_disk -p chain-storage -- --bench
jellyfish_disk, get_with_proof
                        time:   [370.42 us 375.35 us 383.60 us]
```

### CODE REVIEW

**Comment by yihuang** [comment]
> looks ok; for the disk get benchmark, it'll be more interesting to try with different addresses (not only zero-address)

Done

**Comment by leejw51crypto** [comment]
speed is not so fast , can i get speed with other ?

**Comment by leejw51crypto** [comment]
additional benchmark with starling is necessary

**Comment by leejw51crypto** [comment]
i think 
1 insert roughly 0.085 us

**Comment by tomtau** [comment]
> > looks ok; for the disk get benchmark, it'll be more interesting to try with different addresses (not only zero-address)
> 
> Done

I rather meant overall comparisons that it'll be looking up several different addresses in that microbenchmark -- to double check that the time for one particular existing address isn't some sort of the best edge case.

It's ok to merge now -- some further tests will be required later.

> speed is not so fast
> 
> also, In benchmark
> add os, cpu, ram
> 
> i also need benchmark with other merkletrie to compare

@leejw51crypto it seems ok for the account / staking storage, as there updates aren't that frequent  and for querying, it seems fine and one can load-balance. 

For UTXO commitments, it'll need more benchmarking and examination to find out whether the same trie could be used for that purpose, or something different would be preferable for lower overhead.

**Comment by tomtau** [comment]
(for UTXO commitment, one should experiment with a similar UTXO set size to Bitcoin)

**Comment by yihuang** [comment]
> (for UTXO commitment, one should experiment with a similar UTXO set size to Bitcoin)

Bitcoin UTxO size: 70M.
Jellyfish don't support deletion, I double they will support this in the future, so we might need to do this ourselves if we want to support UTxO.

**Comment by yihuang** [comment]
> > > looks ok; for the disk get benchmark, it'll be more interesting to try with different addresses (not only zero-address)
> > 
> > 
> > Done
> 
> I rather meant overall comparisons that it'll be looking up several different addresses in that microbenchmark -- to double check that the time for one particular existing address isn't some sort of the best edge case.
> 
> It's ok to merge now -- some further tests will be required later.

I checked with different addresses manually, the result doesn't change much, because the key is a further hashing of the address, so it will get randomized.

**Pull request merged**
