### PR TITLE
Problem: Outdated and vulnerable hyper dependency

### LINKED ISSUE #825: Problem: duplicate querying of Tendermint RPC
Solution: Remove tendermint HTTP RPC client once Websocket RPC client is stable

### PR DESCRIPTION
**Pull request by devashishdxt**
Solution: Removed tendermint HTTP RPC client and switched from `websocket` to `tungstenite` crate.

Fixes #825.
Relates to #1337. 

Note: There's still `tendermint-rs` which brings in `hyper 0.10.*` dependency.

### CODE REVIEW

**Comment by devashishdxt** [comment]
bors try

**Comment by devashishdxt** [comment]
bors try

**Comment by devashishdxt** [comment]
> looks ok - for .travis.yml, it can perhaps temporarily not have it `travis_terminate 1` on cargo audit with a note:
> 
> ```
> # FIXME: https://github.com/crypto-com/chain/issues/1337
> ```
> 
> the PR that upgrades tendermint-rs can then turn it on again in travis

Added.

**Comment by tomtau** [comment]
perhaps `travis_terminate 0` for now?

**Pull request merged**
