### PR TITLE
Problem (WIP #1616): keypackage not verified in nodejointx / council node data

### PR DESCRIPTION
**Pull request by yihuang**
Solution:
- Add KeyPackage into ConfidentialInit

### CODE REVIEW

**Comment by yihuang** [comment]
> the rename is ok, but there may be more places to fix it: https://travis-ci.org/github/crypto-com/chain/jobs/691008974#L768

yeah, fixed now.

**Comment by yihuang** [comment]
> Build failed:
> 
> * [drone-hw/push](http://13.82.172.109/crypto-com/chain/659)

Fixed

**Comment by devashishdxt** [comment]
bors retry

**Pull request merged**
