### PR TITLE
Problem: (CRO-494) not possible to create unjail transaction in client-cli

### PR DESCRIPTION
**Pull request by leejw51**
Solution: call unjail in cli

### CODE REVIEW

**Comment by leejw51crypto** [comment]
confirmed it is working fine with 4 nodes using HW enclave

**Comment by lezzokafka** [comment]
This PR is more for creating an unjail Tx, which can become part of CRO-494; the test workflow can be something like :

- Run a blockchain with multiple validators
- Let one of the validator nodes go offline, let it reaches the `SIGNING_THRESHOLD` within the `BLOCK_SIGNING_WINDOW`;
- Check if the node is jailed ;
- Check unbounding is impossible when the node is jailed
- Check un-jailing is impossible within the `JAIL_DURATION` by sending un-jailing Tx.
At the end of `JAIL_DURATION` , 
- Check if the staking address was slashed by `LIVENESS_SLASH_RATIO`; 
- Check if can be un-jailed by an un-jail Tx
- Check if the node is back to the validator list (given that the staking amount after the slashing=> `COUNCIL_NODE_MIN_STAKE` )

**Comment by leejw51crypto** [comment]
wallet bug

**Pull request closed without merging**
