### PR TITLE
Problem (Fix #851): no unbonding validator test

### LINKED ISSUE #851: Problem: no integration test for unbonding validator
check that it left the validator set

@leejw51crypto Jason can help with this issue

### LINKED ISSUE #948: Problem: Client has no stable way to wait for successful execution of transaction
Currently, there are different ways to archive this:
- Wait for several blocks(1 is not enough) (using `latest_block_height` of `status` endpoint), not stable.
- Wait for the pending value of wallet balance to become zero, only works for some types of transactions, and assuming there are no concurrent tasks on the same wallet.
- Query `abci_query` with path `meta` and txid. There's no way to detect failure except timeout. Also not all kinds of transactions(deposit) can be queried with it.

It would be good for client-rpc/client-cli to provide the behaviour of `broadcast_tx_commit`.

### PR DESCRIPTION
**Pull request by yihuang**
Solution:
- integrate unbond test into join test.
- use tx_search to wait for transaction (Fix #948)
- change node stopping sequence, try to fix app_hash mismatch problem

### CODE REVIEW

**Comment by tomtau** [comment]
bors try

**Comment by yihuang** [comment]
> looks all right -- not sure if #948 is fixed, as it depends on the node configuration.... in the default configuration I guess the client would need to track / return the tendermint tx id

The original motivation for this issue is for integration tests, maybe when we have cases for other kinds of tasks who don't want to enable index tags, open new issues.

**Pull request merged**
