### PR TITLE
Problem: (CRO-629) Integration tests fails on Travis CI

### PR DESCRIPTION
**Pull request by calvinlauco**
Solution: Run integration tests as mock on Travis CI

### CODE REVIEW

**Comment by devashishdxt** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors retry

**Comment by calvinaco** [comment]
bors try

**Comment by calvinlauco** [comment]
bors try-

**Comment by calvinaco** [comment]
bors try-

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinlauco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Pull request merged**
