### PR TITLE
Problem: Missing runner for TDBE

### PR DESCRIPTION
**Pull request by devashishdxt**
Solution: Created a WIP `TdbeApp` and `spawn_tdbe()` which can be called from `main()` once all the components are ready. Related to #1994, #1995, #2051

### CODE REVIEW

**Comment by tomtau** [comment]
https://github.com/crypto-com/chain/blob/master/chain-abci/src/main.rs#L42

**Comment by devashishdxt** [comment]
> 1. transaction IDs will be fetched by TDBE, not provided from outside -- so it should be provided the remote node's TM RPC from which it can fetch both TX IDs and its TDBE address (it'll just need a chain-abci query endpoint for that)

Won't this be done in #1992?

Just FYI, this is an intermediate PR which adds the base code which was present earlier. It can modified for each issue separately.

**Comment by devashishdxt** [comment]
> > 1. transaction IDs will be fetched by TDBE, not provided from outside -- so it should be provided the remote node's TM RPC from which it can fetch both TX IDs and its TDBE address (it'll just need a chain-abci query endpoint for that)
> 
> Won't this be done in #1992?
> 
> Just FYI, this is an intermediate PR which adds the base code which was present earlier. It can modified for each issue separately.

Or do you think all these related issues should be fixed in a single PR?

**Comment by tomtau** [comment]
> Won't this be done in #1992?
Yes, so this PR should provide something that will help with that -- e.g. runner will be getting/providing RPC config + address that will be exposed via chain-abci query.

> Or do you think all these related issues should be fixed in a single PR?
> Just FYI, this is an intermediate PR which adds the base code which was present earlier. It can modified for each issue separately.

No, but the PR should solve some problem -- if the runner here isn't useful / needs to be replaced in any follow up PRs, this PR can be solved by using the default "ftxsgx-runner" (it won't work, but neither will the runner in this PR)

**Comment by devashishdxt** [comment]
> > Won't this be done in #1992?
> 
> Yes, so this PR should provide something that will help with that (runner needs to be compatible with that) -- e.g. runner will be getting/providing RPC config + address that will be exposed via chain-abci query.
> 
> > Or do you think all these related issues should be fixed in a single PR?
> > Just FYI, this is an intermediate PR which adds the base code which was present earlier. It can modified for each issue separately.
> 
> No, but the PR should solve some problem -- if the runner here isn't useful / needs to be replaced in any follow up PRs, this PR's problem can be solved by using the default "ftxsgx-runner" (it won't work, but neither will the runner in the current state -- and it's simpler, as no new code needs to be added)

Ok. I'll modify. Closing this PR for now.

**Pull request closed without merging**
