### PR TITLE
Problem(Fix #915): no delete wallet API

### LINKED ISSUE #915: Problem: no delete wallet API

### PR DESCRIPTION
**Pull request by yihuang**
Solution:
- Add delete wallet api to both cli and rpc.

### CODE REVIEW

**Comment by yihuang** [comment]
> Delete wallet is a very important action. Once deleted it would mean the funds are gone forever. This is the reason we didn't implement it in the first place.
> 
> How about deleted wallet is kept for certain period at least.

If the user already saved his mnemonic words safely, then it's not so dangerous.

**Comment by calvinlauco** [comment]
> > Delete wallet is a very important action. Once deleted it would mean the funds are gone forever. This is the reason we didn't implement it in the first place.
> > How about deleted wallet is kept for certain period at least.
> 
> If the user already saved his mnemonic words safely, then it's not so dangerous.

Yes I agree, but this is not an easy assumption we can make 🙈

**Comment by tomtau** [comment]
> > Delete wallet is a very important action. Once deleted it would mean the funds are gone forever. This is the reason we didn't implement it in the first place.
> > How about deleted wallet is kept for certain period at least.
> 
> If the user already saved his mnemonic words safely, then it's not so dangerous.

The default wallet option isn't deterministic, so has no seed and mnemonic words -- perhaps a delete for that type should be disabled until there's a "import/export keys" function?

**Comment by yihuang** [comment]
> can you rebase the changes on the latest master?

done

**Comment by yihuang** [comment]
> > > Delete wallet is a very important action. Once deleted it would mean the funds are gone forever. This is the reason we didn't implement it in the first place.
> > > How about deleted wallet is kept for certain period at least.
> > 
> > 
> > If the user already saved his mnemonic words safely, then it's not so dangerous.
> 
> The default wallet option isn't deterministic, so has no seed and mnemonic words -- perhaps a delete for that type should be disabled until there's a "import/export keys" function?

Maybe open another issue to import/export the basic wallet?

**Comment by tomtau** [comment]
> > > > Delete wallet is a very important action. Once deleted it would mean the funds are gone forever. This is the reason we didn't implement it in the first place.
> > > > How about deleted wallet is kept for certain period at least.
> > > 
> > > 
> > > If the user already saved his mnemonic words safely, then it's not so dangerous.
> > 
> > 
> > The default wallet option isn't deterministic, so has no seed and mnemonic words -- perhaps a delete for that type should be disabled until there's a "import/export keys" function?
> 
> Maybe open another issue to import/export the basic wallet?

https://github.com/crypto-com/chain/issues/827

**Pull request merged**
