### PR TITLE
Problem: (CRO-634) from_cro in ExtendedAddress ignores network

### PR DESCRIPTION
**Pull request by calvinlauco**
Solution: Add network human readable prefix check

### CODE REVIEW

**Comment by calvinaco** [comment]
Receiving error from a transistive dependency of `tendermint`
```
error[E0432]: unresolved import `rand`
--
2729 |  
2730 | --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-dalek-1.0.0-pre.3/src/ed25519.rs:14:5
2731 |  
2732 | \|
2733 |  
2734 | 14 \| use rand::{CryptoRng, RngCore};
2735 |  
2736 | \|     ^^^^ use of undeclared type or module `rand`
2737 |  
2738 |  
2739 | error[E0432]: unresolved import `rand`
2740 |  
2741 | --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-dalek-1.0.0-pre.3/src/secret.rs:22:5
2742 |  
2743 | \|
2744 |  
2745 | 22 \| use rand::{CryptoRng, RngCore};
2746 |  
2747 | \|     ^^^^ use of undeclared type or module `rand`
2748 |  
2749 |  
2750 | error: aborting due to 2 previous errors
```

which is unrelated to the code changes. I will retry and see if it persists.

**Comment by calvinaco** [comment]
bors retry

**Comment by calvinaco** [comment]
bors try

**Comment by tomtau** [comment]
bors try

**Comment by calvinaco** [comment]
> rebase on top of the latest master

Done

**Pull request merged**
