### PR TITLE
Problem:(CRO-447) there is no reset state after disconnection in autosync

### PR DESCRIPTION
**Pull request by leejw51crypto**
Solution: add reset state to ready after disconnection

### CODE REVIEW

**Comment by lezzokafka** [comment]
Have just set up a continuous test for this, no worries :)

**Comment by leejw51crypto** [comment]
ok

**Comment by leejw51crypto** [comment]
added reconnection unit test

**Comment by leejw51crypto** [comment]
i'm inspecting travis

**Comment by tomtau** [comment]
@calvinaco it seems the same issue with the integration test here https://github.com/crypto-com/chain/pull/402#issuecomment-533980049

**Comment by calvinaco** [comment]
I can reproduce the integration test error under local mode. It should be a code problem.

chain-abci
```
[2019-09-23T18:22:46Z INFO  chain_abci::app] received query request
[2019-09-23T18:22:46Z WARN  chain_abci::app::query] received a temporary *mock* encryption/decryption query in abci
[2019-09-23T18:22:46Z INFO  chain_abci::app] received query request
[2019-09-23T18:22:46Z INFO  chain_abci::app] received query request
[2019-09-23T18:22:46Z WARN  chain_abci::app::query] received a temporary *mock* encryption/decryption query in abci
[2019-09-23T18:22:46Z INFO  chain_abci::app] received checktx request
[2019-09-23T18:22:46Z INFO  chain_abci::app] received beginblock request
[2019-09-23T18:22:46Z INFO  chain_abci::app] received delivertx request
[2019-09-23T18:22:46Z INFO  chain_abci::app] received endblock request
[2019-09-23T18:22:46Z INFO  chain_abci::app] received commit request
thread 'tokio-runtime-worker-0' panicked at 'persisting enclave storage failed', chain-abci/src/app/commit.rs:135:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::begin_panic
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:411
   8: chain_abci::app::commit::<impl chain_abci::app::app_init::ChainNodeApp<T>>::commit_handler
             at chain-abci/src/app/commit.rs:135
   9: chain_abci::app::<impl abci::Application for chain_abci::app::app_init::ChainNodeApp<T>>::commit
             at chain-abci/src/app/mod.rs:293
  10: abci::server::respond
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/abci-0.6.1/src/server.rs:79
  11: abci::server::serve::{{closure}}::{{closure}}
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/abci-0.6.1/src/server.rs:37
  12: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/function.rs:279
  13: core::option::Option<T>::map
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/option.rs:416
  14: <futures::stream::map::Map<S,F> as futures::stream::Stream>::poll
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/stream/map.rs:79
  15: <futures::stream::fold::Fold<S,F,Fut,T> as futures::future::Future>::poll
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/stream/fold.rs:56
  16: futures::future::chain::Chain<A,B,C>::poll
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/chain.rs:26
  17: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/then.rs:32
  18: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/mod.rs:113
  19: futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329
  20: futures::task_impl::Spawn<T>::enter::{{closure}}
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399
  21: futures::task_impl::std::set
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/std/mod.rs:83
  22: futures::task_impl::Spawn<T>::enter
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399
  23: futures::task_impl::Spawn<T>::poll_fn_notify
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:291
  24: futures::task_impl::Spawn<T>::poll_future_notify
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329
  25: tokio_threadpool::task::Task::run::{{closure}}
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/task/mod.rs:145
  26: core::ops::function::FnOnce::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/function.rs:231
  27: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:315
  28: std::panicking::try::do_call
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:296
  29: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  30: std::panicking::try
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:275
  31: std::panic::catch_unwind
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:394
  32: tokio_threadpool::task::Task::run
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/task/mod.rs:130
  33: tokio_threadpool::worker::Worker::run_task2
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/worker/mod.rs:567
  34: tokio_threadpool::worker::Worker::run_task
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/worker/mod.rs:459
  35: tokio_threadpool::worker::Worker::try_steal_task
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/worker/mod.rs:416
  36: tokio_threadpool::worker::Worker::try_run_task
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/worker/mod.rs:301
  37: tokio_threadpool::worker::Worker::run
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/worker/mod.rs:241
  38: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:390
  39: tokio_timer::timer::handle::with_default::{{closure}}
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/timer/handle.rs:101
  40: std::thread::local::LocalKey<T>::try_with
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/thread/local.rs:257
  41: std::thread::local::LocalKey<T>::with
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/thread/local.rs:234
  42: tokio_timer::timer::handle::with_default
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/timer/handle.rs:84
  43: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:382
  44: tokio_timer::clock::clock::with_default::{{closure}}
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/clock/clock.rs:137
  45: std::thread::local::LocalKey<T>::try_with
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/thread/local.rs:257
  46: std::thread::local::LocalKey<T>::with
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/thread/local.rs:234
  47: tokio_timer::clock::clock::with_default
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/clock/clock.rs:117
  48: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:381
  49: tokio_reactor::with_default::{{closure}}
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.9/src/lib.rs:237
  50: std::thread::local::LocalKey<T>::try_with
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/thread/local.rs:257
  51: std::thread::local::LocalKey<T>::with
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/thread/local.rs:234
  52: tokio_reactor::with_default
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.9/src/lib.rs:217
  53: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:380
  54: tokio_threadpool::callback::Callback::call
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/callback.rs:22
  55: tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/worker/mod.rs:127
  56: tokio_executor::global::with_default::{{closure}}
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.8/src/global.rs:209
  57: std::thread::local::LocalKey<T>::try_with
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/thread/local.rs:257
  58: std::thread::local::LocalKey<T>::with
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/thread/local.rs:234
  59: tokio_executor::global::with_default
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.8/src/global.rs:178
  60: tokio_threadpool::worker::Worker::do_run::{{closure}}
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/worker/mod.rs:125
  61: std::thread::local::LocalKey<T>::try_with
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/thread/local.rs:257
  62: std::thread::local::LocalKey<T>::with
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/thread/local.rs:234
  63: tokio_threadpool::worker::Worker::do_run
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/worker/mod.rs:116
  64: tokio_threadpool::pool::Pool::spawn_thread::{{closure}}
             at /Users/hei/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/pool/mod.rs:344
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

Tendermint
```
I[2019-09-23|18:22:45.310] Committed state                              module=state height=72 txs=0 appHash=D7315954BB523806FD208FBAEAC89A00BE6A734CFC70C31195869CDFB7E26D8C
I[2019-09-23|18:22:46.463] Executed block                               module=state height=73 validTxs=1 invalidTxs=0
E[2019-09-23|18:22:46.493] Stopping abci.socketClient for error: EOF    module=abci-client connection=consensus
E[2019-09-23|18:22:46.495] Client error during proxyAppConn.CommitSync  module=state err=EOF
E[2019-09-23|18:22:46.496] Error on ApplyBlock. Did the application crash? Please restart tendermint module=consensus err="Commit failed for application: EOF"
I[2019-09-23|18:22:46.502] captured terminated, exiting...              module=main
I[2019-09-23|18:22:46.502] Stopping Node                                module=main impl=Node
I[2019-09-23|18:22:46.502] Stopping Node                                module=main
E[2019-09-23|18:22:46.502] Not stopping BlockPool -- have not been started yet module=blockchain impl=BlockPool
I[2019-09-23|18:22:46.507] Closing rpc listener                         module=main listener="&{Listener:0xc00000e4f8 sem:0xc0000787e0 closeOnce:{m:{state:0 sema:0} done:0} done:
```

**Comment by calvinaco** [comment]
I couldn't troubleshoot the origin of the error yet. Will continue with Jongwhan tomorrow.

**Comment by tomtau** [comment]
> I can reproduce the integration test error under local mode. It should be a code problem.
> 

that seems strange, as this auto sync code didn't change anything in chain-abci and doesn't submit any extra abci-related requests (afaik) -- the error returned is that the enclave wrapper tries to flush (make sure its persisted on disk) its local DB on block commit, but that failed for some reason, so possibly some container setup

**Comment by tomtau** [comment]
I'll merge this -- the integration test stuff can be resolved in https://github.com/crypto-com/chain/pull/413

**Pull request merged**
