### PR TITLE
Problem: Unbonding any amount removes a validator

### PR DESCRIPTION
**Pull request by devashishdxt**
Solution: Changed new voting power assignment logic. Fixes https://github.com/crypto-com/chain/issues/910

Note: Logic is slightly different than the one in issue description.

### CODE REVIEW

**Comment by tomtau** [comment]
A few other test cases:
unbond large amount (less than min)
AND
A. deposit the same amount -> no validator update
B. deposit different amounts larger than min -> validator update to that amount
C. deposit amount smaller than min -> validator update to 0

**Comment by lezzokafka** [comment]
> A few other test cases:
> unbond large amount (less than min)
> AND
> A. deposit the same amount -> no validator update
> B. deposit different amounts larger than min -> validator update to that amount
> C. deposit amount smaller than min -> validator update to 0

 Would it works only if the `Unbond` and `Deposit` Tx are in the same block?

**Comment by tomtau** [comment]
> > A few other test cases:
> > unbond large amount (less than min)
> > AND
> > A. deposit the same amount -> no validator update
> > B. deposit different amounts larger than min -> validator update to that amount
> > C. deposit amount smaller than min -> validator update to 0
> 
> Would it works only if the `Unbond` and `Deposit` Tx are in the same block?
> 
> **Edit**: should be all right as validator update is not (and should not) happen often .

yes, that test was in the context of one block

**Comment by devashishdxt** [comment]
Closing this PR. Will reopen once all the testcases are completed.

**Pull request closed without merging**
