### PR TITLE
Problem: tree-math implementation don't take advantage of std functions

### PR DESCRIPTION
**Pull request by yihuang**
Solution:
- use leading_trailing_ones apis

### CODE REVIEW

**Review by tomtau — APPROVED** [review]
bors r+

**Comment by yihuang** [comment]
fixed clippy issue.

**Comment by tomtau** [comment]
bors retry

**Comment by tomtau** [comment]
bors retry

**Comment by tomtau** [comment]
```
error[E0658]: use of unstable library feature 'leading_trailing_ones'
272	   --> chain-tx-enclave-next/mls/src/tree_math.rs:302:7
273	    |
274	302 |     x.trailing_ones()
275	    |       ^^^^^^^^^^^^^
276	    |
277	    = note: see issue #57969 <https://github.com/rust-lang/rust/issues/57969> for more information
278	    = help: add `#![feature(leading_trailing_ones)]` to the crate attributes to enable
279	
280	error: aborting due to previous error
281	
```
there's a bit older version of nightly on drone, so can be updated later with this -- will temporarily close this pr for now

**Pull request closed without merging**
