### PR TITLE
Problem:(CRO-540) syncing does not work in HD wallet

### PR DESCRIPTION
**Pull request by leejw51**
Solution: add private, public keys to storage

### CODE REVIEW

**Comment by leejw51crypto** [comment]
yets,
it's in another PR,
i will work on that PR first.

**Comment by leejw51crypto** [comment]
viewkey == transfer address[0]

**Comment by tomtau** [comment]
the build may fail due to https://github.com/crypto-com/chain/pull/595

**Comment by tomtau** [comment]
bors retry

**Pull request merged**
