### PR TITLE
Problem: (CRO-643) client-rpc does not retry connections to tendermint

### PR DESCRIPTION
**Pull request by devashishdxt**
Solution: Added retry logic in case of I/O failure

Sample log message:

```
[2019-12-12T09:00:20Z ERROR client_rpc::server] Initialization error: Unable to connect to websocket RPC at: ws://localhost:26657/websocket
     => WebSocketError: I/O failure
```

### CODE REVIEW

**Comment by yihuang** [comment]
Do we embed retry behavior like this to all services? 
Another solution if using some sort of process manager to re-start the whole thing whatever reason it crashes.
Sometimes, it might be a bit of confusion when process just hanging there when it can't start.

**Comment by tomtau** [comment]
> Do we embed retry behavior like this to all services?
> Another solution is using some sort of process manager to re-start the whole thing whatever reason it crashes.
> Sometimes, it might be a bit of confusion when process just hanging there when it can't start.

@yihuang yeah, I agree that infinite looping is a bit confusing -- if someone runs this and doesn't set up an alert for error logs, they may come back to a seemingly running process, but they'll just see a log spammed with errors that it couldn't connect.
Ideally, there should be some exponential backoff or upper bound on retries, after which it gives up -- could be improved in a different PR

**Comment by yihuang** [comment]
> > Do we embed retry behavior like this to all services?
> > Another solution is using some sort of process manager to re-start the whole thing whatever reason it crashes.
> > Sometimes, it might be a bit of confusion when process just hanging there when it can't start.
> 
> @yihuang yeah, I agree that infinite looping is a bit confusing -- if someone runs this and doesn't set up an alert for error logs, they may come back to a seemingly running process, but they'll just see a log spammed with errors that it couldn't connect.
> Ideally, there should be some exponential backoff or upper bound on retries, after which it gives up -- could be improved in a different PR

Or add an option to make it optional, I guess this feature is mainly for the convenience of development?

**Comment by tomtau** [comment]
I suppose the original motivation was development / integration tests, so making it optional is an option as well :)

**Pull request merged**
