### PR TITLE
Problem: (CRO-374) CLI uses base units for amounts

### PR DESCRIPTION
**Pull request by devashishdxt**
**Solution**: Changed client to accept amount in CRO

**Note**: As a long term solution to this, we should change `FromStr` implementation of `Coin`.

### CODE REVIEW

**Comment by leejw51crypto** [comment]
how about force using .0 or .00
decimal point for numbers?

to remove mis-understanding completely

**Comment by devashishdxt** [comment]
> how about force using .0 or .00
> decimal point for numbers?
> 
> to remove mis-understanding completely

@tomtau What do you think?

**Comment by tomtau** [comment]
> > how about force using .0 or .00
> > decimal point for numbers?
> > to remove mis-understanding completely
> 
> @tomtau What do you think?

How is it in the Angular UI sample wallet? I think either way is fine as long as it's consistent among human interfaces

**Comment by devashishdxt** [comment]
> > > how about force using .0 or .00
> > > decimal point for numbers?
> > > to remove mis-understanding completely
> > 
> > 
> > @tomtau What do you think?
> 
> How is it in the Angular UI sample wallet? I think either way is fine as long as it's consistent among human interfaces

Current implementation is same as Angular UI

**Pull request merged**
