### PR TITLE
Problem: (CRO-602) Integration tests local mode sometimes not working

### PR DESCRIPTION
**Pull request by calvinlauco**
Solution: Fix prepare script execution order and start script bugs

---
Remarks:
- While in long term we are migrating to using the python bot, but I want to fix the current issues such that it works seamlessly first.

### CODE REVIEW

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors retry

**Comment by tomtau** [comment]
bors retry

**Comment by tomtau** [comment]
bors retry

**Pull request merged**
