### PR TITLE
Problem (Fix #1188): WalletSyncer doesn't support callback to report progress

### LINKED ISSUE #1188: Problem: WalletSyncer doesn't support callback to report progress
Currently it only support channel progress reporter, it's not as flexible as callback, with callback, you don't have to spawn a thread.
And channel style can be implemented on top of callback.

### PR DESCRIPTION
**Pull request by yihuang**
Solution:
- Add progress_callback
- Remove progress_reporter

### CODE REVIEW

**Comment by leejw51crypto** [comment]
lgtm

**Comment by leejw51crypto** [comment]
let sync_callback = SyncCallback {
        user_data,
        user_callback: dummy,
    };
    let sync_rpc = SyncRpcImpl::new(syncer_config, Some(sync_callback));
    let wallet_rpc = WalletRpcImpl::new(wallet_client, network_id);

could you add to new or  set_callback(..)?
thanks!

**Comment by yihuang** [comment]
> seems there are some errors for the http-based sync: https://travis-ci.org/crypto-com/chain/jobs/658261443#L785

The unit test failure is fixed now.

> 
> there's this older issue for that #825

**Pull request merged**
