### PR TITLE
Problem: slow wallet operation for over 4,000,000 addresses (fix #1922)

### LINKED ISSUE #1922: Problem: slow wallet operation for over 4,000,000 addresses
remove un-necessary wallet loading, fix other logic to improve speed

### PR DESCRIPTION
**Pull request by leejw51crypto**
refactoring to improve sync speed ,
load_wallet now called only in export, import

1. changed load_wallet called only in export, import
2.  update Wallet in address recovering instead of fetching all

### CODE REVIEW

**Comment by tomtau** [comment]
bors try

**Comment by leejw51crypto** [comment]
fixing travis issue

**Comment by tomtau** [comment]
bors retry

**Comment by tomtau** [comment]
bors retry

**Comment by tomtau** [comment]
bors try

**Comment by tomtau** [comment]
seemed to be caused by https://github.com/crypto-com/chain/issues/1934

**Comment by leejw51crypto** [comment]
ok

**Comment by tomtau** [comment]
bors try

**Comment by leejw51crypto** [comment]
working on again
let transfer_addresses = wallet.transfer_addresses();

**Pull request merged**
